language: python
sudo: false
matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 2.7
          env: PURE_PYTHON=1
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6
          env: WITH_COVERAGE=1
        - os: linux
          python: 3.6
          env:
            - PURE_PYTHON=1
            - WITH_COVERAGE=1
        - os: linux
          python: 3.7-dev
        - os: linux
          python: pypy
        - os: linux
          python: pypy3
        # It's important to use 'macpython' builds to get the least
        # restrictive wheel tag. It's also important to avoid
        # 'homebrew 3' because it floats instead of being a specific version.
        - os: osx
          language: generic
          env: TERRYFY_PYTHON='macpython 2.7'
        - os: osx
          language: generic
          env: TERRYFY_PYTHON='macpython 3.4'
        - os: osx
          language: generic
          env: TERRYFY_PYTHON='macpython 3.5'
        - os: osx
          language: generic
          env: TERRYFY_PYTHON='macpython 3.6.0'
        - services:
            - docker
          env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
          before_install:
            - if [[ $TRAVIS_TAG ]]; then bash .manylinux.sh; fi
            - exit 0
        - services:
            - docker
          env:
            - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
            - PRE_CMD=linux32
          before_install:
            - if [[ $TRAVIS_TAG ]]; then bash .manylinux.sh; fi
            - exit 0

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git clone https://github.com/MacPython/terryfy; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source terryfy/travis_tools.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then get_python_environment $TERRYFY_PYTHON venv; fi
install:
    - pip install -U pip setuptools
    # persistent is a setup_requires, which gets downloaded by
    # setuptools, not pip. But macpython 3.6.0 setuptools has trouble with SSL on
    # Travis CI
    # (https://travis-ci.org/zopefoundation/BTrees/jobs/192340692) so
    # we install with pip manually.
    - pip install -U persistent
    - if [[ "$WITH_COVERAGE" == "1" ]]; then pip install coveralls coverage; fi
    - pip install -e .[test,ZODB]
script:
    - if [[ "$WITH_COVERAGE" == "1" ]]; coverage run -m zope.testrunner --test-path=. --auto-color --auto-progress --verbose; else zope-testrunner --test-path=. --auto-color --auto-progress; fi
notifications:
    email: false
after_success:
    - if [[ "$WITH_COVERAGE" == "1" ]]; coveralls; fi
    - echo [distutils]                                  > ~/.pypirc
    - echo index-servers = pypi                        >> ~/.pypirc
    - echo [pypi]                                      >> ~/.pypirc
    - echo username=zope.wheelbuilder                  >> ~/.pypirc
    - echo password=$PYPIPASSWORD                      >> ~/.pypirc
    - if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "osx" ]]; then pip install twine; fi
    - if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "osx" ]]; then python setup.py bdist_wheel; fi
    - if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "osx" ]]; then twine upload dist/*; fi

env:
    global:
        secure: "Oh5gRJ+Fo8ZNmCkdrffpx201EPyTr9iUXmv6VqJMTebrzQpFdSWUVcANRmAzyfdyk3Wo0IjifVfWsKc+hvtbFmXZiLRFyEgoCUmzeWVumjebg2xxm0PbFHcRQgl4daBXxB0iqWkP8wXZ3daytuL74sYcbHizMYyhc7AxFbANsZc="

cache: pip
